apiVersion: v1
kind: ConfigMap
metadata:
  name: node
  namespace: default
data:
  HOSTNAME: "0.0.0.0"
  PORT: "3000"
  HOSTNAME_HELLO: node-hello
  PORT2: "4000"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-hello
  labels:
    app: node-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-hello
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
        - name: hello-container
          image: ivantorrellas/node_hello:latest
          ports:
          - containerPort: 3000
            protocol: TCP
            name: hello-port
          envFrom:
          - configMapRef:
              name: node
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: node-hello
  namespace: default
spec:
  type: NodePort
  selector:
    app: node-hello
  ports:
  - port: 3000
    nodePort: 30300
    targetPort: 3000
