apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-reversed
  labels:
    app: node-reversed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-reversed
  template:
    metadata:
      labels:
        app: node-reversed
    spec:
      containers:
        - name: reversed-container
          image: ivantorrellas/node_reversed:latest
          ports:
          - containerPort: 4000
            protocol: TCP
            name: reversed-port
          envFrom:
          - configMapRef:
              name: node
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: node-reversed
  namespace: default
spec:
  type: NodePort
  selector:
    app: node-reversed
  ports:
  - port: 4000
    nodePort: 30400
    targetPort: 4000
